Add agent user to sudoers
monasca/monasca-agents-installer pull request #11
Opened 2017-10-23 11:23 UTC by haruki-yamanashi

Auto-detection for postfix was failed because agent user couldn't access
postfix directory so this change adds root authorization to agent user.
Add agent user to sudoers to execute monasca-setup command properly.

2017-10-23 11:24 UTC, haruki-yamanashi commented
@samirjorina @digitalfishpond @witekest

2017-10-24 12:01 UTC, samirjorina requested changes

2017-10-24 12:01 UTC, samirjorina commented on configure_metrics_agent.sh
> +  sudo echo "mon-agent ALL=(ALL) NOPASSWD:ALL" >> ${MON_SUDUERS_FILE}
Here I get an error:
```
$ sudo echo "mon-agent ALL=(ALL) NOPASSWD:ALL" >> ${MON_SUDUERS_FILE}
-bash: /etc/sudoers.d/mon-agent: Permission denied
```

2017-10-25 04:37 UTC, haruki-yamanashi commented on configure_metrics_agent.sh
> +  sudo echo "mon-agent ALL=(ALL) NOPASSWD:ALL" >> ${MON_SUDUERS_FILE}
Done.

2017-10-25 09:10 UTC, samirjorina approved these changes

2017-10-25 09:10 UTC, merged